### ISSUE TITLE
increase view area in layer

### ISSUE THREAD

**Issue by mgiraldo** [nypl-spacetime/nypl-warper#22]
similar to #11 but for [`app/views/layouts/layerdetail.html.erb`](https://github.com/nypl-spacetime/nypl-warper/blob/master/app/views/layouts/layerdetail.html.erb)

see: http://maps.nypl.org/warper/layers/1138

**Comment by lklepner** [comment]
I can take this on. Can you advise on loading sample data to the dev server?

**Comment by lklepner** [comment]
I increased the view area of the Show tab using the same approach as the Preview tab of the Maps layout -
http://mapwarper.livefeed.net/warper/layers/1

I'm unclear how the Digitize is operated. In both the prod example and my local dev example I don't see any data -
![google chromescreensnapz023](https://cloud.githubusercontent.com/assets/110027/14351516/c7dc8a54-fc9d-11e5-81b0-f8069c0bc76c.png)

**Comment by mgiraldo** [comment]
you can create a layer out of any group of maps. so you could for example make three maps out of that original one (1+2 insets)

**Comment by lklepner** [comment]
layers are clear now (and awesome!) but the digitizer is still a mystery... most because I'm having a hard time finding an example of it in action.

**Comment by lklepner** [comment]
submitted a PR for the Show tab changes - https://github.com/nypl-spacetime/nypl-warper/pull/24

**Comment by mgiraldo** [comment]
it's where you draw map features (building footprints or roads)

**Comment by lklepner** [comment]
Tracing over the map right? Any idea why the left side is blank? Do I need
to preset it I some way?

**Comment by mgiraldo** [comment]
you select a "layer" to work on... this is a vector layer... select "Buildings" and then click on the "Draw polygons" tool (top right trapezoid) and click away in the map

this digitizer is somewhat complicated/confusing to use… but it has been our workhorse for many years

**Comment by mgiraldo** [comment]
fixed in e45d60a00955defae1852f831762627061c185d0
