### ISSUE TITLE
Rectify Method is not saved

### ISSUE THREAD

**Issue by lklepner** [nypl-spacetime/nypl-warper#27]
I've noticed that the rectify method is not being saved - ff the page is reloaded the rectification approach returns to the default setting and if the map is cropped the default rectification method is used. 

This is a problem because some maps yield much better results with non-default rectification types.

In the case of one of the Hudson River Atlas maps (http://maps.nypl.org/warper/maps/14911) the river is significantly compressed on the map to make room for additional inland space (see note overlaid on the river itself). Thin Plate Spline yields much better results in this case than the auto rectification setting... but the improvement will not be retained in the long run since a page refresh or crop operation will return the rectify method to the original setting. 

Thin Plate Spline -
![screen shot 2016-04-08 at 8 33 28 am](https://cloud.githubusercontent.com/assets/110027/14383754/127092b4-fd65-11e5-8afb-79c8cb00f5dd.png)

After reloading the page, allowing the rectify method to change back to auto -
![google chromescreensnapz026](https://cloud.githubusercontent.com/assets/110027/14383783/40b8e5cc-fd65-11e5-871b-277ea8f3ed75.png)

**Comment by mgiraldo** [comment]
good catch. i'd say this is a bug and we need to fix that

**Comment by mgiraldo** [comment]
this is fixed now: http://maps.nypl.org/warper/maps/14911

<img width="1033" alt="rectified" src="https://cloud.githubusercontent.com/assets/133020/15232014/685fed9c-186c-11e6-97d7-857f68df161e.png">

<img width="552" alt="saved" src="https://cloud.githubusercontent.com/assets/133020/15232029/7e581fb6-186c-11e6-8cd9-c76e80d72523.png">

**Comment by lklepner** [comment]
Maps are re-rectified when cropped. I tested that route and got the default/wrong result.

**Comment by mgiraldo** [comment]
I suppose you did not modify the select boxes? only pressed rectify in the rectify tab?

can you provide the steps to reproduce because I tried several times and this is the result I get after refreshing:

**Comment by mgiraldo** [comment]
oh I think I know what you're talking about 

I will look into that. a new bug needs to be filled for that 

- mga

**Comment by mgiraldo** [comment]
fixed in #51 👍

**Comment by lklepner** [comment]
confirmed - thanks!
