### ISSUE TITLE
Layer bounds problem?

### ISSUE THREAD

**Issue by lklepner** [nypl-spacetime/nypl-warper#28]
Searching for layers by location I noticed this one -
http://maps.nypl.org/warper/layers/872

The bounds seem to be extremely large for some reason. I re-rectified a problem map (http://maps.nypl.org/warper/maps/8153) whose outline had stretched across the atlantic.. but it seems like the bounds of the layer itself have not updated.

**Comment by mgiraldo** [comment]
this looks fixed to me. could be a wrong cropping in the sheet?

**Comment by lklepner** [comment]
Looks good now - I'll close the issue
