### ISSUE TITLE
Map 9604 needs insets

### ISSUE THREAD

**Issue by lklepner** [nypl-spacetime/nypl-warper#29]
Checking out layer 878 ( http://maps.nypl.org/warper/layers/878 ) I noticed that the outlines of one of the maps ( http://maps.nypl.org/warper/maps/8604) stretched up to Albany though it really features a series of sections of eastern Long Island. Should a series of insets be created for this map?

There is a larger question here as well.. which is how to set people up for success rectifying maps with insets. As things stand a first time user or even moderately experience user would be hard pressed to handle a map with insets correctly. If this is something you'd like to delve into I'd be happy to explore the UI/UX of a workflow which improves this experience.

**Comment by mgiraldo** [comment]
this seems to be an inset case. apparently the current control points produce that high-boundary result. it's true that insets can be very confusing for new users and that the current tool does not provide a good solution, but for now this has a solution: delete the secondary set of control points and create 5 insets.

**Comment by lklepner** [comment]
Deleted the second set of control points as a fix for this particular map.
