### ISSUE TITLE
Map 19004 - permissions problem?

### ISSUE THREAD

**Issue by lklepner** [nypl-spacetime/nypl-warper#30]
Rectify / crop tabs are missing 
http://maps.nypl.org/warper/maps/19004

![google chromescreensnapz028](https://cloud.githubusercontent.com/assets/110027/14387004/477769fa-fd75-11e5-8634-789fcc159eed.png)

**Comment by mgiraldo** [comment]
i can see them now. you might have not been logged in?

**Comment by lklepner** [comment]
I'm still seeing the issue when I confirm that I'm logged in.

**Comment by mgiraldo** [comment]
oh... the reason you cannot see the tabs is because it is "Published". an admin determined this map is finished and published it. this makes the map un-alterable by non-admins. publishing moves map tiles to S3 and affects other workflows so that's why it cannot be altered.

**Comment by lklepner** [comment]
Ahh I see. Thanks for clarifying.
