### ISSUE TITLE
Map 8351 - Broken image?

### ISSUE THREAD

**Issue by lklepner** [nypl-spacetime/nypl-warper#32]
Zooming in/out and refreshing the page did not cause the image in this map to load properly -
http://maps.nypl.org/warper/maps/8351

![google chromescreensnapz029](https://cloud.githubusercontent.com/assets/110027/14388138/ad3948bc-fd7a-11e5-9afe-1aa5d301d304.png)

**Comment by mgiraldo** [comment]
fixed. byproduct of our recent disk space issue.
