### ISSUE TITLE
Crops lost at some point?

### ISSUE THREAD

**Issue by lklepner** [nypl-spacetime/nypl-warper#37]
I've noticed a decent number of maps which had crop outlines but the crop was not applied to the preview. Here is an example - 
http://maps.nypl.org/warper/maps/15297

Unless creating crops and applying crops was recently condensed into one step... it seems like crops might have been lost at some point reverting instead to the uncropped image?

**Comment by mgiraldo** [comment]
this might be related to a recent problem we had with the warper where it ran out of disk space. the solution was to apply the crop ("Mask Map" button) and the tiles were re-generated. we will fix these issues as we identify them. thanks for catching this one.

(that map is pretty badly rectified btw but that's another issue)

**Comment by lklepner** [comment]
Good to know about the disk space problem. I'd noticed several maps with this setup and wondered what happened. 

The rectification on this map isn't actually that bad -- its that the rectify method is defaulting back to auto / polynominal when cropped which produce a really bad results when it really needs Thin Plate Spline to work with these control points. 

Thin Plate -
![google chromescreensnapz038](https://cloud.githubusercontent.com/assets/110027/14649282/4925c13a-0634-11e6-84e7-a01bda7534e0.png)

Auto - 
![google chromescreensnapz037](https://cloud.githubusercontent.com/assets/110027/14649283/4926b7d4-0634-11e6-9112-4e4ef6b788c5.png)

**Comment by lklepner** [comment]
I wonder if it would make sense to run a job which re-executed the crop for all maps with a crop outline? 

I've noticed a few layers where most of the maps have outlines that weren't applied, like this one -
http://maps.nypl.org/warper/layers/878

There is a significant downside to doing this though... every map would be reverted to the auto rectification method since rectification methods haven't been getting saved. Maybe the rectification method should begin getting stored first.

**Comment by mgiraldo** [comment]
yeah. saving of rectification method should be top priority

On Tue, Apr 19, 2016 at 10:51 AM, Lou Klepner <notifications@github.com>
wrote:

> I wonder if it would make sense to run a job which re-executed the crop
> for all maps with a crop outline?
>
> I've noticed a few layers where most of the maps have outlines that
> weren't applied, like this one -
> http://maps.nypl.org/warper/layers/878
>
> There is a significant downside to doing this though... every map would be
> reverted to the auto rectification method since rectification methods
> haven't been getting saved. Maybe the rectification method should begin
> getting stored first.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/nypl-spacetime/nypl-warper/issues/37#issuecomment-212039565>
>



-- 
Mauricio
