### ISSUE TITLE
map with wrong crop

### ISSUE THREAD

**Issue by mgiraldo** [nypl-spacetime/nypl-warper#42]
http://maps.nypl.org/warper/maps/15173#Preview_tab

**Comment by lklepner** [comment]
I've found that if there are two outlines which overlap the overlapping area is subtracted. In the case of this map someone outlined the area map area AND the land areas were also outlined.  

I went ahead and deleted the map outline so the land area mask would be applied, the result of which looks pretty good -

![screen shot 2016-04-30 at 9 49 22 am](https://cloud.githubusercontent.com/assets/110027/14936355/f873b9ee-0eb8-11e6-8e59-3b8ad17311e8.png)


![screen shot 2016-04-30 at 9 49 32 am](https://cloud.githubusercontent.com/assets/110027/14936353/f271bda2-0eb8-11e6-8a94-9cf9189eb649.png)

**Comment by lklepner** [comment]
I think this issue can be closed
