### ISSUE TITLE
Adding NYPL Maps to the Warper catalog

### ISSUE THREAD

**Issue by scspaeth** [nypl-spacetime/nypl-warper#72]
The NYPL Digital Collections ( http://digitalcollections.nypl.org ) contain some public domain maps which are not in the Map Warper catalog ( http://maps.nypl.org/warper/maps?utf8=✓&field=text&query= ).
Can authenticated warpers add maps from the digitalcollections to the warper/maps or does that require higher authorization?

**Comment by scspaeth** [comment]
For example, this search in the warper catalog:
http://maps.nypl.org/warper/maps?utf8=%E2%9C%93&field=text&query=Virginia&from=1602&to=1656&show_warped=0
finds the cover pseudo-map:
http://maps.nypl.org/warper/maps/12893
But not the real map from the same source:
http://digitalcollections.nypl.org/items/510d47da-c3c7-a3d9-e040-e00a18064a99

**Comment by mgiraldo** [comment]
it is possible that this Virginia map has not made its run through to the warper because it was just digitized. do you have another example?

**Comment by scspaeth** [comment]
I have another example but it comes from the same source. I'll keep my eyes out for others.
In reference to the current example, how long should it take for it to work through the process and appear in the Warper catalog?

**Comment by mgiraldo** [comment]
the warper image set is updated at the beginning of the month. it is also possible that the map in question was not scanned in as high resolution for it to be useful in the warper. the whole scanning-metadata-web-warper process is rather complicated and many things could be in the way of the map appearing in the warper. i will close this for now. hopefully this map will make its way to the warper soon.

**Comment by scspaeth** [comment]
Thanks for the updates and insights.
