### ISSUE TITLE
Unable to log in with Facebook

### ISSUE THREAD

**Issue by lklepner** [nypl-spacetime/nypl-warper#76]

**Comment by mgiraldo** [comment]
are you getting a specific error?

**Comment by lklepner** [comment]
no error, just a page refresh and the log in doesn't happen

**Comment by mgiraldo** [comment]
not sure if it related to [FB API changes](https://developers.facebook.com/docs/apps/changelog)

🤔

will look into it

**Comment by mgiraldo** [comment]
yeah this could be the issue https://github.com/plataformatec/devise/issues/4478

**Comment by mgiraldo** [comment]
updating to devise 4 fixed this

**Comment by lklepner** [comment]
Confirmed - thanks

On Wed, Jun 28, 2017 at 12:10 PM, Mauricio Giraldo <notifications@github.com
